[package]
name = "success"
version = "0.1.0"
authors = ["Pascal Hertleif <killercup@gmail.com>"]
build = "src/main.rs"
description = "A great crate, much successful"
license = "MIT OR Apache-2.0"

[dependencies]
